version: '3.8'

services:
  finance-backend:
    build:
      context: /finance
      dockerfile: Dockerfile
    command: >
      bash -c "pipenv run python manage.py makemigrations && pipenv run python manage.py migrate && pipenv run python manage.py runserver 0.0.0.0:8000 && pipenv run python manage.py collectstatic"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/finance/static
    networks:
      - my_network
    depends_on:
      - database
    restart: always


  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_PASSWORD=198616Gm
      - POSTGRES_USER=usersup
      - POSTGRES_DB=finance_db
    ports:
      - "5432:5432"
    networks:
      - my_network

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/static/
    networks:
      - my_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my_network

  celery:
    build:
      context: /finance
      dockerfile: Dockerfile
    command: >
      bash -c "pipenv run celery -A conf worker --loglevel=info"
    networks:
      - my_network
    depends_on:
      - finance-backend
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always

volumes:
  static_volume:
  media_volume:



networks:
  my_network:
    driver: bridge


